name: complete-checking

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile the program
        run: |
          make
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the tests
        run: |
          make test algorithm
          make test type_traits
          make test utility
          make test iterator
          make test vector
          make test stack
          make test rb_node
          make test rb_iterator
          make test map
          make test set
